[phases.setup]
packages = ["python3", "python3-venv", "python3-pip"]

[phases.build]
commands = [
  "python -m venv /app/.venv",
  "pip install -r requirements.txt"
]

[phases.start]
commands = [
  "python bot.py"
]
